[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "luigi-gadd"
version = "0.3.0"
license = "MIT"
description = "Provides additional functionality to make Luigi more flexible"
authors = [{ name = "Mike Lynch", email = "me@msl.sh" }]
requires-python = ">=3.9"
dependencies = ["luigi (>=3.0, <4.0)"]

[project.urls]
Homepage = "https://github.com/mikelynch/luigi-gadd"
Repository = "https://github.com/mikelynch/luigi-gadd"

[tool.poetry.group.dev.dependencies]
black = "^24.10"
isort = "^5.13"
mypy = "^1.14"
pytest = "^8.3"
tox = "^4.23"

[tool.black]
line-length = 90

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py39,py310,py311,py312,py313

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v
    poetry run black .
    poetry run isort .
    poetry run mypy src
    poetry run pytest tests/
"""
