[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "luigi-gadd"
version = "0.3.0"
license = "MIT"
description = "Provides additional functionality to make Luigi more flexible"
authors = [{ name = "Mike Lynch", email = "me@msl.sh" }]
requires-python = ">=3.9"
dependencies = ["luigi (>=3.0, <4.0)"]

[project.urls]
Homepage = "https://github.com/mikelynch/luigi-gadd"
Repository = "https://github.com/mikelynch/luigi-gadd"

[tool.poetry.group.dev.dependencies]
mypy = "^1.14"
pytest = "^8.3"
ruff = "^0.9.1"

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
